### ISSUE TITLE
[원자성 검토] 원자성 검토 사항

### ISSUE THREAD

**Issue by d0lim** [2021-caucse-software-engineering/enhanced-library-management#30]
REQ-5 : The system should allow a manager to search guest with guest's ID or name.   
---
- The system should allow a manager to search guest with guest's ID.  
- The system should allow a manager to search guest with guest's name.   
---

REQ-41 : The system shall notify to guests through SMS or E-mail when due date approaches.  
---
- The system shall notify to guests through SMS when due date approaches.  
- The system shall notify to guests through E-mail when due date approaches.  
---

REQ-42 : The system shall allow guests to send feedback with contents anonymously or not.  
---
- The system shall allow guests to send feedback with contents anonymously.
- The system shall allow guests to send feedback with contents non-anonymously.  
---

**Comment by cjdthsus2gh** [comment]
원자성이란 것이 복합 '목적이 아닌 단일 목적을 가져야 한다는 것'인데 위 Req들은 전부 그 옵션에 차이가 있을 뿐 동일한 단일 목적을 가지고 있다고 생각합니다.

**Comment by Beopsik** [comment]
A or B란 표현이 둘 다 선택 가능하다는 중복적인 느낌이 있어서 REQ-5, REQ-42를 두 개로 나누자고 한 것 같습니다. 하지만  either A or B란 표현으로 REQ-5, REQ-42를 수정하면  REQ를 두 개로 나누지 않고 중복적인 느낌을 없앨 수 있다고 생각합니다.  REQ의 표현을 수정하는 방향으로 하면 좋을 것 같습니다.

**Comment by pjs0418** [comment]
req-5는 받아들이겠습니다. req-42는 수정하지 않아도 될 것 같습니다.

**Comment by pjs0418** [comment]
req-41도 맞는 거 같습니다.

**Comment by d0lim** [comment]
해당 내용 취합하여 PR 띄우도록 하겠습니다.
