### ISSUE TITLE
[누락된 요구] 누락된 것 같은 요구에 대한 사항

### ISSUE THREAD

**Issue by d0lim** [2021-caucse-software-engineering/enhanced-library-management#33]
## Isusing List
REQ-10, REQ-11 에서 issuing list 를 언급하는데. issuing list에 대한 설명이 전혀 없어서, 요구가 불명확합니다.  
- 시스템은 대출해줄 책을 임시저장하기 위한 issuing list를 제공한다.  
와 같은 느낌의 요구가 있으면 어떨까 싶습니다.

## Menu
REQ-12에서 calculate fine menu, REQ-20 에서 Feedback menu 라는 것을 언급하는데, 메뉴에 대한 것을 요구에서 지워둔 상황이라, 이를 어떻게 해결하는 것이 좋을지 논의가 필요합니다.

## The list
REQ-35, REQ-37에서 list라는 것을 언급하는데, 해당 list에 대한 내용을 언급해야 할 것 같습니다. 그런데 저희가 해당 건에 대해서 이야기를 나누긴 했는데, 문서로 반영하지 못한 것 같네요. 이에 대한 논의가 필요합니다.

**Comment by pjs0418** [comment]
Issuing list는 동의합니다.
req-12는 삭제하고 대출정보를 매니저에게 제공한다는 뜻인거 같아서 req-13이랑 겹치는 거 같습니다.
req-20은 메뉴 지우고 매니저에게 피드백을 확인할 수 있는 기능을 제공한다로 바꾸면 좋을 거 같습니다.
req-35는 단순하게 정렬한다는 의미에서 listed라는 단어를 쓴 거 같고,
req-37은 e-book 대출 정보를 제거한다는 뜻인 거 같은데, e-book 대출 리스트에서 제거한다던지 정도로 쓰면 되지 않을까요?

**Comment by d0lim** [comment]
그렇네요. REQ-12와 13이 본질적으로 같은 내용인 것 같습니다. 조금 더 구체적인 13을 살리고 12를 삭제하는 것이 옳을 것 같네요.   
REQ-20 포함해서 전반적으로 메뉴라는 표현 자체를 많이 제외하는 것이 좋을 것 같습니다.
REQ-35는 뭐랄까 앞의 한 단계가 생략된 것 같아서요. 리스트가 없는데 리스트된 책을 정렬한다라는게 뭔가 어색하긴 합니다. 
REQ-37은 차라리 못보게 한다라는 뉘앙스로 바꿔보면 어떨까요?

**Comment by cjdthsus2gh** [comment]
Req-35나 Req-37의 list라는 단어를 빼고, Req-35는 책을 정렬할 수 있는 기준을 제공한다 정도의 뉘앙스 정도로 바꾸면 어떨까 싶습니다.
그리고 Req-37은 사실 Req-30이 완전히 대체하는 것 같은데, 이에 대해서 확인 부탁드립니다.

Req-30 : The system shall provide e-book issued information such as title, issue start date, and due date to a guest.

**Comment by yulaseo** [comment]
req-12, req-13, req-20에 관한 내용 동의합니다.
req-30에 관해서는 그러면 책의 표지와 제목 목록들을 display한다는 기능을 추가해야 할까요? 정렬 기능이 눈에 보이는 목록을 대상으로 사용된다고 생각해서요.
그리고 대출 기간이 지나면 e-book을 못보게 하는 것이 e-book 대출 정보를 제공한다는 말로 어떻게 대체되는지 이해가 가지 않습니다!

**Comment by cjdthsus2gh** [comment]
Req-30은 사용자가 빌린 e-book의 대출 정보를 제공한다는 요구인데, 그 말은 "빌린 e-book에 대해서만 대출 정보를 제공한다 = 대출 상태가 아닌 e-book의 정보는 제공하지 않는다" 라고 해석되는 것 같아 언급했습니다.

**Comment by d0lim** [comment]
REQ-30이 대체할 수 있는 내용은 아닌 것 같습니다.  
REQ-30 과 37의 관계는 실물 책 대출에 있어서 대출 정보 제공과 반납의 관계와 같은 것이라서요.  
반납의 기능에 해당하는 것을 제외하긴 힘들 것 같습니다.

**Comment by youngkwon02** [comment]
Req-30은 log형태로 E-Book 열람기한이 지난 이후에도 사용자가 어떤 E-Book을 대여했었는지 조회 가능한 기록이고,
Req-37은 열람가능한 E-Book을 나열한다는 점에서 조금 의미가 다른듯합니다.

30번을 Issued information을 issued history로 변경하고
37번을 from the list -> from the viewable list로 변경해서 의미를 명확히 하는게 어떨까요?

**Comment by yulaseo** [comment]
> REQ-37은 차라리 못보게 한다라는 뉘앙스로 바꿔보면 어떨까요?

이렇게 바꾸면 REQ-34랑 비슷한 맥락인 것 같습니다.

**Comment by cjdthsus2gh** [comment]
> REQ-30이 대체할 수 있는 내용은 아닌 것 같습니다.
> REQ-30 과 37의 관계는 실물 책 대출에 있어서 대출 정보 제공과 반납의 관계와 같은 것이라서요.
> 반납의 기능에 해당하는 것을 제외하긴 힘들 것 같습니다.

그럼 Req-34와 Req-30을 전부 고려해서 Req-37을 "e-book reading period가 지난 e-book은 자동 반납되도록 한다" 정도로 수정하면 어떨까요?

Req-30 : The system shall provide e-book issued information such as title, issue start date, and due date to a guest.
Req-34 : The system shall allow a guest to access e-books only during the e-book reading period.
Req-37 : _"e-book reading period가 지난 e-book은 자동 반납되도록 한다"_

**Comment by pjs0418** [comment]
> Req-30은 log형태로 E-Book 열람기한이 지난 이후에도 사용자가 어떤 E-Book을 대여했었는지 조회 가능한 기록이고,
> Req-37은 열람가능한 E-Book을 나열한다는 점에서 조금 의미가 다른듯합니다.
> 
> 30번을 Issued information을 issued history로 변경하고
> 37번을 from the list -> from the viewable list로 변경해서 의미를 명확히 하는게 어떨까요?


30번이 e-book history를 보여준다기 보다는 현재 대출된 e-book 정보를 제공한다는 게 좀 더 맞는 거 같습니다.
37번 초기 뉘앙스는 e-book 열람 가능 기간이 끝나면 확인할 수 있는 e-book 대출 리스트에서 해당 e-book 정보를 삭제한다는 거였는데 원희 말대로 30번, 34번은 그대로 두고 자동 반납되도록 한다가 가장 괜찮은 거 같습니다.

**Comment by pjs0418** [comment]
저희가 UI적인 요소를 제하다 보니 이해에 혼동이 온 것 같습니다.

**Comment by youngkwon02** [comment]
> > Req-30은 log형태로 E-Book 열람기한이 지난 이후에도 사용자가 어떤 E-Book을 대여했었는지 조회 가능한 기록이고,
> > Req-37은 열람가능한 E-Book을 나열한다는 점에서 조금 의미가 다른듯합니다.
> > 30번을 Issued information을 issued history로 변경하고
> > 37번을 from the list -> from the viewable list로 변경해서 의미를 명확히 하는게 어떨까요?
> 
> 30번이 e-book history를 보여준다기 보다는 현재 대출된 e-book 정보를 제공한다는 게 좀 더 맞는 거 같습니다.
> 37번 초기 뉘앙스는 e-book 열람 가능 기간이 끝나면 확인할 수 있는 e-book 대출 리스트에서 해당 e-book 정보를 삭제한다는 거였는데 원희 말대로 30번, 34번은 그대로 두고 자동 반납되도록 한다가 가장 괜찮은 거 같습니다.

혹시 29번도 paper book의 issued history 조회기능 아닌가요??
29랑 30번 차이가 paper랑 ebook 차이밖에 없는거 같아서요.

**Comment by cjdthsus2gh** [comment]
> 혹시 29번도 paper book의 issued history 조회기능 아닌가요??
> 29랑 30번 차이가 paper랑 ebook 차이밖에 없는거 같아서요.

e-book의 경우는 연체되는 경우가 없다보니 연체되었는지의 여부랑 연체료 정보가 포함되어있지 않습니다.

**Comment by youngkwon02** [comment]
> > 혹시 29번도 paper book의 issued history 조회기능 아닌가요??
> > 29랑 30번 차이가 paper랑 ebook 차이밖에 없는거 같아서요.
> 
> e-book의 경우는 연체되는 경우가 없다보니 연체되었는지의 여부랑 연체료 정보가 포함되어있지 않습니다.

네네. 그럼 기능적으로는 29번과 마찬가지로 여때까지 사용자가 빌린 E-book내역을 보여주는 기능 아닌가요??
준수가 현재 대출된 E-book을 보여준다고 했는데, E-book열람기한이 끝나면 30번 List에서 사라진다는 말인가요?!?

**Comment by Beopsik** [comment]
> > REQ-30이 대체할 수 있는 내용은 아닌 것 같습니다.
> > REQ-30 과 37의 관계는 실물 책 대출에 있어서 대출 정보 제공과 반납의 관계와 같은 것이라서요.
> > 반납의 기능에 해당하는 것을 제외하긴 힘들 것 같습니다.
> 
> 그럼 Req-34와 Req-30을 전부 고려해서 Req-37을 "e-book reading period가 지난 e-book은 자동 반납되도록 한다" 정도로 수정하면 어떨까요?
> 
> Req-30 : The system shall provide e-book issued information such as title, issue start date, and due date to a guest.
> Req-34 : The system shall allow a guest to access e-books only during the e-book reading period.
> Req-37 : _"e-book reading period가 지난 e-book은 자동 반납되도록 한다"_

저도 REQ-37을 자동반납으로 수정하는게 맞다고 생각합니다.

**Comment by cjdthsus2gh** [comment]
> 네네. 그럼 기능적으로는 29번과 마찬가지로 여때까지 사용자가 빌린 E-book내역을 보여주는 기능 아닌가요??
> 준수가 현재 대출된 E-book을 보여준다고 했는데, E-book열람기한이 끝나면 30번 List에서 사라진다는 말인가요?!?

원자성 측면에서 두 개가 따로 분리되어있는 것 같고 기능적으로는 똑같은 게 맞습니다.
e-book 열람기한이 끝나면 30번 List에서 사라지는 것도 맞고 그것 때문에 위에서 제가 37번을 대체할 수 있다고 생각을 했던건데, 자동으로 사라지는걸 더 명확하게 표현하기 위해서 Req-30을 약간 수정해도 좋을 것 같습니다. 

Req-30 : The system shall provide _"자신이 대출한 책의 정보"_ such as title, issue start date, and due date to a guest.

안1)Req-34 : The system shall allow a guest to access e-books only during the e-book reading period. 
안2)Req-34 : The system shall allow a guest to access e-books if only _E-book을 대출한 경우에만_

Req-37 : "e-book reading period가 지난 e-book은 자동 반납되도록 한다"

정도면 어떨까요?

**Comment by pjs0418** [comment]
req-29, 30에 게스트가 대출한 책이다 정도의 정보를 추가하는 건 괜찮은 거 같습니다.

안2 보다는 안1이 맞는 거 같습니다.

req-37도 동의합니다.

**Comment by d0lim** [comment]
> > > 혹시 29번도 paper book의 issued history 조회기능 아닌가요??
> > > 29랑 30번 차이가 paper랑 ebook 차이밖에 없는거 같아서요.
> > 
> > 
> > e-book의 경우는 연체되는 경우가 없다보니 연체되었는지의 여부랑 연체료 정보가 포함되어있지 않습니다.
> 
> 네네. 그럼 기능적으로는 29번과 마찬가지로 여때까지 사용자가 빌린 E-book내역을 보여주는 기능 아닌가요??
> 준수가 현재 대출된 E-book을 보여준다고 했는데, E-book열람기한이 끝나면 30번 List에서 사라진다는 말인가요?!?

@youngkwon02  지금까지의 모든 history가 아니라, 일단은 현재 대출 상태의 책들을 보여주는 기능입니다.

**Comment by d0lim** [comment]
> > 네네. 그럼 기능적으로는 29번과 마찬가지로 여때까지 사용자가 빌린 E-book내역을 보여주는 기능 아닌가요??
> > 준수가 현재 대출된 E-book을 보여준다고 했는데, E-book열람기한이 끝나면 30번 List에서 사라진다는 말인가요?!?
> 
> 원자성 측면에서 두 개가 따로 분리되어있는 것 같고 기능적으로는 똑같은 게 맞습니다.
> e-book 열람기한이 끝나면 30번 List에서 사라지는 것도 맞고 그것 때문에 위에서 제가 37번을 대체할 수 있다고 생각을 했던건데, 자동으로 사라지는걸 더 명확하게 표현하기 위해서 Req-30을 약간 수정해도 좋을 것 같습니다.
> 
> Req-30 : The system shall provide _"자신이 대출한 책의 정보"_ such as title, issue start date, and due date to a guest.
> 
> 안1)Req-34 : The system shall allow a guest to access e-books only during the e-book reading period.
> 안2)Req-34 : The system shall allow a guest to access e-books if only _E-book을 대출한 경우에만_
> 
> Req-37 : "e-book reading period가 지난 e-book은 자동 반납되도록 한다"
> 
> 정도면 어떨까요?

@cjdthsus2gh REQ-30 동의합니다. REQ-34는 그러면  
안3)Req-34 : The system shall allow a guest to access e-books if only E-book이 현재 대출 상태인 경우에만  
으로 하면 어떨까요?

REQ-37도 동의합니다.

**Comment by Beopsik** [comment]
> > 네네. 그럼 기능적으로는 29번과 마찬가지로 여때까지 사용자가 빌린 E-book내역을 보여주는 기능 아닌가요??
> > 준수가 현재 대출된 E-book을 보여준다고 했는데, E-book열람기한이 끝나면 30번 List에서 사라진다는 말인가요?!?
> 
> 원자성 측면에서 두 개가 따로 분리되어있는 것 같고 기능적으로는 똑같은 게 맞습니다.
> e-book 열람기한이 끝나면 30번 List에서 사라지는 것도 맞고 그것 때문에 위에서 제가 37번을 대체할 수 있다고 생각을 했던건데, 자동으로 사라지는걸 더 명확하게 표현하기 위해서 Req-30을 약간 수정해도 좋을 것 같습니다.
> 
> Req-30 : The system shall provide _"자신이 대출한 책의 정보"_ such as title, issue start date, and due date to a guest.
> 
> 안1)Req-34 : The system shall allow a guest to access e-books only during the e-book reading period.
> 안2)Req-34 : The system shall allow a guest to access e-books if only _E-book을 대출한 경우에만_
> 
> Req-37 : "e-book reading period가 지난 e-book은 자동 반납되도록 한다"
> 
> 정도면 어떨까요?



> > > 네네. 그럼 기능적으로는 29번과 마찬가지로 여때까지 사용자가 빌린 E-book내역을 보여주는 기능 아닌가요??
> > > 준수가 현재 대출된 E-book을 보여준다고 했는데, E-book열람기한이 끝나면 30번 List에서 사라진다는 말인가요?!?
> > 
> > 
> > 원자성 측면에서 두 개가 따로 분리되어있는 것 같고 기능적으로는 똑같은 게 맞습니다.
> > e-book 열람기한이 끝나면 30번 List에서 사라지는 것도 맞고 그것 때문에 위에서 제가 37번을 대체할 수 있다고 생각을 했던건데, 자동으로 사라지는걸 더 명확하게 표현하기 위해서 Req-30을 약간 수정해도 좋을 것 같습니다.
> > Req-30 : The system shall provide _"자신이 대출한 책의 정보"_ such as title, issue start date, and due date to a guest.
> > 안1)Req-34 : The system shall allow a guest to access e-books only during the e-book reading period.
> > 안2)Req-34 : The system shall allow a guest to access e-books if only _E-book을 대출한 경우에만_
> > Req-37 : "e-book reading period가 지난 e-book은 자동 반납되도록 한다"
> > 정도면 어떨까요?
> 
> @cjdthsus2gh REQ-30 동의합니다. REQ-34는 그러면
> 안3)Req-34 : The system shall allow a guest to access e-books if only E-book이 현재 대출 상태인 경우에만
> 으로 하면 어떨까요?
> 
> REQ-37도 동의합니다.

안2의 E-book을 대출한 경우에만의 표현보다는 안3의 E-book이 현재 대출 상태인 경우에만으로 바꾸는게 더 정확한 의미라고 생각해서 안3이 맞는거 같습니다.

**Comment by cjdthsus2gh** [comment]
위 수정에 모두 동의합니다

**Comment by pjs0418** [comment]
동의합니다.

**Comment by yulaseo** [comment]
동의합니다

**Comment by youngkwon02** [comment]
넵 확인했습니다~
동의합니다!

**Comment by d0lim** [comment]
넵, 그럼 반영해서 수정 PR 올리겠습니다!
