### ISSUE TITLE
완전성 이슈

### ISSUE THREAD

**Issue by yulaseo** [2021-caucse-software-engineering/enhanced-library-management#34]
REQ-8 : The system shall provide guest's information such as profile photo, name, ID, phone number, current issue restriction state to a manager.
---
- book issue information 추가
- The system shall provide a manager with guest's information such as profile photo, name, ID, phone number, current issue restriction state, and book issue information.

REQ-14 : The system shall calculate fine based on issue period and overdue days.
---
- 대출 기간 고려 삭제, 책 별로 연체일 고려 추가
- The system shall calculate fine based on overdue days per book.

REQ-19 : The system should allow a manager to send notification to long overdue guests about book issue overdue.
---
- notification 방법에 대한 자세한 내용 추가
- The system should allow a manager to send notification to long overdue guests about book issue overdue using SMS.
- The system should allow a manager to send notification to long overdue guests about book issue overdue using E-mail.

Req-23 : The system should alert a manager when deleting the guest if the guest is overdue for any book.
---
- 어떤 Alert Message 내용을 띄우는가 명시
- The  system should alert a warning message to confirm whether the manager really want to delete a guest or not who has not returned a book yet.

Req-26 : The system shall provide the guest's ID to the manager automatically when adding a guest.
---
- Automatically가 provide와 묶여서, guest ID에 대한 정보가 부족
- The system shall automatically make a new ID for the new guest and provide it to the manager when manager is trying to add the new guest.

Req-38 : The system should provide the function for extending the rental period to a guest.
---
- 어떤 종류의 책을 연장하는 기능인지 명시하여 완전성 확보 (extending the paper book rental period / extending the E-book rental period)
- 이후 각각을 분리하여 원자성 확보.

Req-41 : The system shall notify to guests through SMS or E-mail when due date approaches.
---
- notify message 명시
- The system shall notify to guests about the due date is coming through SMS or E-mail when due date approaches.

**Comment by cjdthsus2gh** [comment]
https://github.com/2021-caucse-software-engineering/enhanced-library-management/issues/30#issue-854981798
Req-19는 위 원자성 이슈에서 정해진 대로 기술하면 어떨까 싶습니다.
이외 모든 Req 동의합니다.

**Comment by d0lim** [comment]
모든 REQ 동의합니다.  
원자성 확보까지 고려해주시는 섬세함에 감동받았습니다.

**Comment by Beopsik** [comment]
모든 REQ에 동의합니다.

**Comment by yulaseo** [comment]
그러면 REQ-19는 하나로 통합해서 전체 내용 적용하겠습니다!

**Comment by pjs0418** [comment]
이하 동문입니다.

**Comment by d0lim** [comment]
> 그러면 REQ-19는 하나로 통합해서 전체 내용 적용하겠습니다!

어 그런데, REQ-41 하나 하나 쪼개서 반영하였는데요! REQ-19도 쪼개서 하는게 맞을 것 같습니다,

**Comment by yulaseo** [comment]
모두 확인하고 반영했습니다!
