### ISSUE TITLE
추가 논의사항 제안

### ISSUE THREAD

**Issue by yulaseo** [2021-caucse-software-engineering/enhanced-library-management#36]
REQ-6 : The system shall consider input value as ID if the manager's input value is composed of digits when a manager searches for guest.
---
- 영어 문장 간결하게 수정
- The system shall consider an input value as guest's ID if a manager searches a guest with digits.

REQ-7 : The system shall consider input value as guest's name if the manager's input value is composed of letters when a manager searches for a guest.
---
- 영어 문장 간결하게 수정
- The system shall consider input value as guest's name if a manager searches a guest with letters.

REQ-9 : The system should provide a function to search books to users.
---
- 모호한 해석 수정
- The system should provide a user with a function to search books.

REQ-12 : The system shall allow a manager to check the book issue information after a book is issued at calculate fine menu.
---
- 영어 해석+통일성 문제
- 해석의 모호함에 있어서 at calculate fine menu 빼는 게 어떤지 (책이 calcualte fine 메뉴에서 대출되었다는 것 같음), 그리고 다른 req들은 이제 어떤 메뉴에서 실행되는지 기술 안하니까.

REQ-12, 13
---
- 내용중복+완전성
- 이 둘은 12에서는 '책이 대출된 후'를 강조했다는 점 말고는 같은 요구를 기술하고 있는 느낌임. 12에는 information에 대한 설명이 없어서 완전성도 부족한 느낌이지만 13에 설명되므로 두 번 말하는 것도 아닌 것 같음. 12는 없애는 게 나을까?

REQ-17 : The system should provide overdue guests list sorted decrement by overdue days to a manager.
---
- 영작 수정
- The system should provide overdue guests list sorted in descending order by overdue days to a manager. 

REQ-20 : The system shall show a manager guest's feedback on check feedback menu.
---
- '체크 피드백 메뉴에서'를 설명해야할까?

REQ-27 : The system shall restrict a manager from adding a guest if the guest is already a registered member.
---
- 이미 등록된 회원임을 구별하는 기준에 대해서는 명시하지 않아도 될까?

**Comment by d0lim** [comment]
REQ-12, 13에 대한 내용은 #33 에서 함께 논의해보면 좋을 것 같습니당

**Comment by d0lim** [comment]
REQ-6, 7, 17 너무 아름다워서 눈물이 납니다 ㅠㅠ  
REQ-9 문서 작성 중에 provide a with b 와 provide b to a 둘 중 하나로 통일하는게 좋을 것 같아서 고민이 있었는데, 확실히 의미의 혼동보다는 각각 적절한 표현을 사용하는 게 맞을 것 같네요.  
REQ-20 관한 논의도 #33 과 통합하면 될 것 같습니다.  
REQ-27 관해서는 등록된 회원임을 구별하는 기준을 넣으면 오히려 너무 구체적이지 않을까요? 이건 다른 분들의 의견도 궁금하네요. @Beopsik @cjdthsus2gh @pjs0418 @youngkwon02

**Comment by youngkwon02** [comment]
저도 Provide는 문장에 따라 to랑 사용할지, with랑 사용할지 선택적으로 작성해야 할 듯합니다.
Req-27에서 이미 가입한 회원을 구별하는게, 별도의 기준이 있나요??
만약 기준이 아니구 어떻게 중복회원을 구별할건지를 말씀하시는거면 기술적인 부분에 가깝다고 생각해서
굳이 명시 안하는게 어떨까 생각합니다.

**Comment by yulaseo** [comment]
> Req-27에서 이미 가입한 회원을 구별하는게, 별도의 기준이 있나요??
> 만약 기준이 아니구 어떻게 중복회원을 구별할건지를 말씀하시는거면 기술적인 부분에 가깝다고 생각해서
> 굳이 명시 안하는게 어떨까 생각합니다.

기술적인 부분이 어떤 건지 잘 감이 오지 않습니다만, 예를 들어 생년월일+이름, 주민등록번호 같은 구별 기준이 필요할지에 대해 얘기해보고 싶었습니다.

**Comment by cjdthsus2gh** [comment]
중복회원을 구별하는 기준이 NF로 들어가도 괜찮을 것 같긴 한데, 구현만으로도 끝나는 문제라 굳이 안써도 될 것 같긴 합니다.

**Comment by pjs0418** [comment]
네 저도 어떻게 구별할 지에 대한 부분은 기술하지 않아도 되지 않을까...라고 생각합니다.

**Comment by d0lim** [comment]
일단 REQ-27의 구별 기준은 넘어간 다음에 Use Cases를 작성할 때 너무 명시적이지 않은 부분이 있으면 추가하는 방향으로 하는게 어떨까요?

**Comment by yulaseo** [comment]
네 그러면 다른 이슈에서 언급된 req-12, 13, 20과 수정하지 않는 방향으로 의견이 모인 req-27 제외하고 나머지 부분 반영하도록 하겠습니다~~

**Comment by d0lim** [comment]
> 네 그러면 다른 이슈에서 언급된 req-12, 13, 20과 수정하지 않는 방향으로 의견이 모인 req-27 제외하고 나머지 부분 반영하도록 하겠습니다~~

넵 알겠습니다!
