### ISSUE TITLE
Req21 ~ Req 43 비모호성과 통일성 검토 및 문법적 오류 수정

### ISSUE THREAD

**Issue by pjs0418** [2021-caucse-software-engineering/enhanced-library-management#37]
## Req-24
a guest -> guests 수정

## Req-27
from adding a guest -> for adding a guest? 라는 식으로 바꾸는 게 나을 거 같습니다. from은 좀 어색한 거 같네요.

그 외에 좀 어색한 부분들이 있는데 너무 자잘해서 나중에 쭉 보고 또 고치는 게 나을 거 같습니다.

**Comment by yulaseo** [comment]
restrict a manager from adding a guest의 문법 구조가 매니저가 게스트를 추가하는 것을 막는다(제한한다)는 의미라서 적절하다고 생각합니다! restrict를 적용해서 어색한 거라면 prevent, prohibit 등으로 바꿔 생각해도 좋을 것 같아요

**Comment by youngkwon02** [comment]
> restrict a manager from adding a guest의 문법 구조가 매니저가 게스트를 추가하는 것을 막는다(제한한다)는 의미라서 적절하다고 생각합니다! restrict를 적용해서 어색한 거라면 prevent, prohibit 등으로 바꿔 생각해도 좋을 것 같아요

동의합니다.
prevent managers to add a guest ...  이런식으로 작성하면 from안써도 의미는 큰 차이 없는거 같습니다.

**Comment by Beopsik** [comment]
> restrict a manager from adding a guest의 문법 구조가 매니저가 게스트를 추가하는 것을 막는다(제한한다)는 의미라서 적절하다고 생각합니다! restrict를 적용해서 어색한 거라면 prevent, prohibit 등으로 바꿔 생각해도 좋을 것 같아요

prevent나 prohibit으로 바꾸는 것에 동의합니다.

**Comment by d0lim** [comment]
예기치 못한 현상이 발생할 것을 대비해서 막는 뉘앙스를 살려서 Prevent로 가는게 어떨까 싶습니다.

**Comment by Beopsik** [comment]
> 예기치 못한 현상이 발생할 것을 대비해서 막는 뉘앙스를 살려서 Prevent로 가는게 어떨까 싶습니다.

prevent가 예기치 못한 상황을 미리 막는다는 느낌이 있으니까 prevent로 가는거에 좋다고 생각합니다.

**Comment by pjs0418** [comment]
옙 수정하겠습니다.
