### ISSUE TITLE
문장 수정 제안

### ISSUE THREAD

**Issue by youngkwon02** [2021-caucse-software-engineering/enhanced-library-management#38]
기존 Req-25 : The system shall provide a function to a manager for adding a guest in the system with the guest's name, phone number, password, profile image, and e-mail.
수정 Req-25 : The system shall provide managers with a function for adding guest in the system using the guest’s name, phone number, password, profile image and e-mail.
- 기능과 어떤 기능인지 설명하는 part 사이에 manager가 껴있어서 가독성에 있어서 provide to보다 provide with 사용이 적절하다고 생각합니다.

기존 Req-35 : Alphabetic order
수정 Req-35 : Dictionary order
- Dictionary order가 더 포괄적이고 적절하다고 생각합니다.

---
Req-23 관련 내용은 #34 에 이미 다룬 내용이라 제외했습니다.

**Comment by Beopsik** [comment]
> 기존 Req-23 : The system should **alert a manager** when deleting the guest if the guest is overdue for any book.
> 수정 Req-23 : The system should **display a warning message to the manager** when deleting the guest if the guest is overdue for a book.
> 
> * Alert를 warning message로 구체화
> 
> 기존 Req-25 : The system shall provide a function to a manager for adding a guest in the system with the guest's name, phone number, password, profile image, and e-mail.
> 수정 Req-25 : The system shall provide managers with a function for adding guest in the system using the guest’s name, phone number, password, profile image and e-mail.
> 
> * 기능과 어떤 기능인지 설명하는 part 사이에 manager가 껴있어서 가독성에 있어서 provide to보다 provide with 사용이 적절하다고 생각합니다.
> 
> 기존 Req-35 : Alphabetic order
> 수정 Req-35 : Dictionary order
> 
> * Dictionary order가 더 포괄적이고 적절하다고 생각합니다.

REQ-23, REQ-25, REQ-35 다 동의합니다.

**Comment by pjs0418** [comment]
동의합니다.

**Comment by d0lim** [comment]
REQ-25, 35 모두 동의합니다.
