### ISSUE TITLE
[비모호성과 통일성] Req01 ~ Req27 검토 사항

### ISSUE THREAD

**Issue by cjdthsus2gh** [2021-caucse-software-engineering/enhanced-library-management#45]
## Req03 - The system shall allow a manager to add a book with the information of a book, such as a title, author, cover image, description, price, quantity, location in the library, E-book file, and ID which is made automatically.

- 모든 정보가 자동으로 생성된다고 해석될수도 있을 것 같아 간단히 수정
- ID which is made automatically => Automatically generated ID

## Req15 - The system should restrict a guest who has overdue book issue depending on overdue days.
- 구체적으로 어떤 행동을 못하게 제한한다는 말이 없는데 대출 제한이란 말인가요 로그인 제한이란 뜻인가요?
- req24는 시스템에서 사용자를 제한한다고 명시가 되어있는데 그럼 15의 경우는 대출 제한이 맞을까요?

## Req17 - The system should provide overdue guests list sorted decrement by overdue days to a manager.
- 가독성을 고려한 영작 수정
- ~~ provide **list of overdued guests** sorted decrement by **overdued** days to ~~~

## Req18, Req19, Req19-2 
- 영작 수정
- overdue guest => overdued guest / overdue days => overdued days

**Comment by Beopsik** [comment]
Req-15의 경우엔 로그인 제한보다는 대출 제한이 맞는거 같습니다.

**Comment by yulaseo** [comment]
REQ-03 동의합니다!
REQ-15 저는 '제한'이라는 말이 모두 대출 제한을 의미해야 한다고 생각합니다.
REQ-17 앞선 이슈에서 수정된 부분을 고려해 The system should provide list of overdued guests sorted in descending order by overdued days to a manager. 으로 변경하면 될 것 같습니다!

**Comment by cjdthsus2gh** [comment]
Req15 - The system should restrict a overdued guest from issuing books depending on overdue days. 정도면 어떨까요?

**Comment by Beopsik** [comment]
The system should restrict an overdue guest from issuing books depending on overdue days. 문법 수정해서 이렇게 하면 될거 같습니다.

**Comment by cjdthsus2gh** [comment]
overdue가 형용사였네요 관련 Req는 전부 취소하면 될것같습니다

**Comment by d0lim** [comment]
> Req15 - The system should restrict a overdued guest from issuing books depending on overdue days. 정도면 어떨까요?

@cjdthsus2gh 언급해주신대로 overdued만 overdue로 변경하면 될 것 같습니다!

**Comment by d0lim** [comment]
REQ-17 에서도 the list of overdue guests 로 하면 될 것 같습니다!
Grammarly에서 문법 한번 체크해보셔도 좋을 것 같아요.

**Comment by youngkwon02** [comment]
Req-03 동의합니다. 앞서 #34 에서도 automatically position관련해서 수정한 부분 있었는데 03번도 마찬가지인거같습니다.
그리고 Req-15를 포함한 모든 제한기능은 다 도서대출 제한이 적절한거같습니다.
로그인도 못하도록 제한할 사유가 딱히 없을거같아서요!
