### ISSUE TITLE
단수 복수 통일성

### ISSUE THREAD

**Issue by d0lim** [2021-caucse-software-engineering/enhanced-library-management#50]
PR  #49 번 리뷰 중에 제안해주신 내용입니다.

a manager, a guest, managers, guests, users 같은 단수/복수에 대한 일정한 기준이나 통일성에 대해 논의가 필요해 보입니다.

요구 전체에 전반적으로 단수 복수가 만발해있어서 의미상 혼동을 일으킬 수 있을 것 같습니다.

**Comment by yulaseo** [comment]
개인적으로 list로 묶여있는 경우를 제외하고는 모두 단수가 좋다고 생각합니다!

**Comment by pjs0418** [comment]
저는 보통은 단수 사용하고, 의미적으로 복수여야 할 때 복수로 썼었는데 기준을 정하면 될 것 같습니다.

**Comment by d0lim** [comment]
기준을 정한다면 


> 개인적으로 list로 묶여있는 경우를 제외하고는 모두 단수가 좋다고 생각합니다!

의 기준을 적용해보면 괜찮을 것 같은데, 어떨까요? @pjs0418 @yulaseo @Beopsik @cjdthsus2gh @youngkwon02

**Comment by cjdthsus2gh** [comment]
동의합니다

**Comment by youngkwon02** [comment]
> 기준을 정한다면
> 
> > 개인적으로 list로 묶여있는 경우를 제외하고는 모두 단수가 좋다고 생각합니다!
> 
> 의 기준을 적용해보면 괜찮을 것 같은데, 어떨까요? @pjs0418 @yulaseo @Beopsik @cjdthsus2gh @youngkwon02

동의합니다

**Comment by Beopsik** [comment]
동의합니다

**Comment by pjs0418** [comment]
동의합니다.

**Comment by d0lim** [comment]
그러면, 아무래도 영어 문장 자체를 포괄하는 내용이니 다른 Issue들이 일단 해결되고 나서 수정 PR 띄우도록 하겠습니다.
