### ISSUE TITLE
REQ-9 완전성 및 비모호성 이슈

### ISSUE THREAD

**Issue by d0lim** [2021-caucse-software-engineering/enhanced-library-management#52]
REQ-9에서 사용자는 책을 검색할 수 있게 한다라는 내용이 어떤 것을 input으로 받아서 검색을 할 수 있다는 것인지 명시가 되어 있지 않아서 완전성이 부족하고 조금 모호한 것 같습니다.
이렇게 한 데에 어떤 이유가 있었으려나요? 혹시 이유가 있었는지, 그게 아니라면 어떻게 바꾸면 될지 의견이 궁금하여 Issue로 올립니다.

**Comment by pjs0418** [comment]
그러네여 위에 사용자 검색은 어떻게 하고 시스템이 어떻게 인식하는지까지 써져 있는데 책 검색은 좀 모호하게 써져 있네요.

**Comment by Beopsik** [comment]
동의합니다. 책 제목이나 작가 등 어떤 input으로 책을 검색 할 수 있는지 정해야할 거 같습니다.

**Comment by youngkwon02** [comment]
무엇으로 검색을 허용할지 먼저 설정한 다음에, 두개 이상의 검색 항목을 체택하기로 결정하면
원자성 고려해서 두개의 Req로 나누면 될거같습니다.
저는 책 제목이랑 작가 이름으로 나눠서 검색 허용하면 충분하다고 생각합니다.
가격이나 출판일자 같은거로 검색하는 사람은 없을거 같네요.
심지어 가격은 이미 filter function이 제공되니까 더더욱 필요 없을거같아요!

**Comment by d0lim** [comment]
@pjs0418 @Beopsik @youngkwon02 그러면 책 제목과 작가로 나누어서  
시스템은 사용자에게 제목을 입력받아 책을 검색할 수 있는 기능을 제공한다.  
시스템은 사용자에게 작가의 이름을 입력받아 책을 검색할 수 있는 기능을 제공한다.  
고 나누어보면 될까요?

**Comment by pjs0418** [comment]
좋습니다

**Comment by youngkwon02** [comment]
> @pjs0418 @Beopsik @youngkwon02 그러면 책 제목과 작가로 나누어서
> 시스템은 사용자에게 제목을 입력받아 책을 검색할 수 있는 기능을 제공한다.
> 시스템은 사용자에게 작가의 이름을 입력받아 책을 검색할 수 있는 기능을 제공한다.
> 고 나누어보면 될까요?

좋습니다~

**Comment by yulaseo** [comment]
동의합니다!

**Comment by d0lim** [comment]
@Beopsik @pjs0418 @youngkwon02 @yulaseo @cjdthsus2gh PR 확인 부탁드립니다!
