### ISSUE TITLE
Guest Feedback 작성 메뉴에서 모호한 부분 논의

### ISSUE THREAD

**Issue by pjs0418** [2021-caucse-software-engineering/enhanced-library-management#53]
Guest가 피드백을 작성하는 메뉴 화면에서 과거에 자신이 작성했던 feedback log를 보여줘야 할 거 같은데 이와 관련한 requirement가 없는 거 같아서 논의가 필요해 보입니다.

**Comment by youngkwon02** [comment]
Feedback이 게시판 형태로 존재한다고 하지 않았나요?!?
만약 게시판형태면 게시판에 Feedback 내역이 남으니까 굳이 로그를 제공할 필요가 있을까 싶기도...
근데 비공개글로 작성했을 때, 본인이 작성한 비공개글이면 본인한테는 보여야 하긴 하는데
이건 굳이 Req에 작성하지 않아도, 비밀글을 지원한다는 Req에 약간 종속되는 느낌?이라서...
말씀하신대로 따로 Req작성해도 좋고, 안해도 괜찮을거같습니다.

**Comment by d0lim** [comment]
> Feedback이 게시판 형태로 존재한다고 하지 않았나요?!?
> 만약 게시판형태면 게시판에 Feedback 내역이 남으니까 굳이 로그를 제공할 필요가 있을까 싶기도...
> 근데 비공개글로 작성했을 때, 본인이 작성한 비공개글이면 본인한테는 보여야 하긴 하는데
> 이건 굳이 Req에 작성하지 않아도, 비밀글을 지원한다는 Req에 약간 종속되는 느낌?이라서...
> 말씀하신대로 따로 Req작성해도 좋고, 안해도 괜찮을거같습니다.

이 이슈가 아마 화면의 UI Requirements를 작성하다가 의문이 들어서 올렸던 이슈입니다.   
저희가 1:1로 매니저와 게스트가 피드백을 교환하게 잡았다 보니, 게시판의 형태 보다는 1:1 문의와 그에 대한 답변 형태로 달리게 될 것 같아서요.  그래서 익명에 대한 이슈는 조금 제칠 수 있을 것 같습니다.
이것까지만 생각을 하고 UI Requirements를 짜다 보면 다음의 의문을 가지게 됩니다.  
1. Guest의 Feedback 화면에서는 Feedback을 입력할 수 있는 Text input만을 가지고 있어야 하나?
2. 아니면 일전에 보낸 Feedback의 답장을 볼 수 있게 이전에 보낸 Feedback을 보여주어야 하나?

당연히 저희의 시나리오에 따르면 후자가 옳겠죠.   
그렇지만 저희 요구사항에는 이전에 남겼던 피드백에 대한 정보를 제공한다 등의 REQ가 없어서요. 이런 REQ를 추가하면 어떨까 하는 의견인 것 같습니다. 저는 남겨주는게 조금 더 명확할 것 같아요.

**Comment by pjs0418** [comment]
아 답변을 작성하고 있었는데 위에 비슷한 생각의 답변이 달렸네요. 다른 분들의 의견 궁금합니다.

**Comment by Beopsik** [comment]
이전 피드백 정보를 보여주는 것이 맞다고 생각합니다.

**Comment by youngkwon02** [comment]
> > Feedback이 게시판 형태로 존재한다고 하지 않았나요?!?
> > 만약 게시판형태면 게시판에 Feedback 내역이 남으니까 굳이 로그를 제공할 필요가 있을까 싶기도...
> > 근데 비공개글로 작성했을 때, 본인이 작성한 비공개글이면 본인한테는 보여야 하긴 하는데
> > 이건 굳이 Req에 작성하지 않아도, 비밀글을 지원한다는 Req에 약간 종속되는 느낌?이라서...
> > 말씀하신대로 따로 Req작성해도 좋고, 안해도 괜찮을거같습니다.
> 
> 이 이슈가 아마 화면의 UI Requirements를 작성하다가 의문이 들어서 올렸던 이슈입니다.
> 저희가 1:1로 매니저와 게스트가 피드백을 교환하게 잡았다 보니, 게시판의 형태 보다는 1:1 문의와 그에 대한 답변 형태로 달리게 될 것 같아서요. 그래서 익명에 대한 이슈는 조금 제칠 수 있을 것 같습니다.
> 이것까지만 생각을 하고 UI Requirements를 짜다 보면 다음의 의문을 가지게 됩니다.
> 
> 1. Guest의 Feedback 화면에서는 Feedback을 입력할 수 있는 Text input만을 가지고 있어야 하나?
> 2. 아니면 일전에 보낸 Feedback의 답장을 볼 수 있게 이전에 보낸 Feedback을 보여주어야 하나?
> 
> 당연히 저희의 시나리오에 따르면 후자가 옳겠죠.
> 그렇지만 저희 요구사항에는 이전에 남겼던 피드백에 대한 정보를 제공한다 등의 REQ가 없어서요. 이런 REQ를 추가하면 어떨까 하는 의견인 것 같습니다. 저는 남겨주는게 조금 더 명확할 것 같아요.


저는 지금 저희가 사용하는 Git Issue와 같이 Guest가 Feedback을 남기면 Manager가 그에 댓글을 달고,
추가적인 질문이 있으면, Guest가 다시 답글을 남기는 식으로 소통한다고 생각해서, 굳이 보여주려 하지 않아도 볼수 있지 않나
생각했었는데, 만약 쪽지형식? 으로 1:1 대화 형식의 Feedback을 제공할거라면, 저도 이전 피드백에 대해 보여주는게 맞다고 생각합니다.

**Comment by d0lim** [comment]
> 저는 지금 저희가 사용하는 Git Issue와 같이 Guest가 Feedback을 남기면 Manager가 그에 댓글을 달고,
> 추가적인 질문이 있으면, Guest가 다시 답글을 남기는 식으로 소통한다고 생각해서, 굳이 보여주려 하지 않아도 볼수 있지 않나
> 생각했었는데, 만약 쪽지형식? 으로 1:1 대화 형식의 Feedback을 제공할거라면, 저도 이전 피드백에 대해 보여주는게 맞다고 생각합니다.

네, 아무래도 커뮤니티로써 작용할 수도 있는 기능은 과감히 배제하자는 의견이 있었어서 쪽지 형태의 1:1 대화 내지 QnA 형태로 갈 것 같습니다.

**Comment by yulaseo** [comment]
쪽지 형태라면 네이버 메일/쪽지함처럼 주고받은 피드백과 답변을 다 저장하고 볼 수 있게 하는 게 맞는 것 같습니다. REQ 추가에 동의합니다.

**Comment by cjdthsus2gh** [comment]
위에 똑같은 요지의 답변이 실시간으로 달렸네요...저 역시 동의합니다.

**Comment by youngkwon02** [comment]
> > 저는 지금 저희가 사용하는 Git Issue와 같이 Guest가 Feedback을 남기면 Manager가 그에 댓글을 달고,
> > 추가적인 질문이 있으면, Guest가 다시 답글을 남기는 식으로 소통한다고 생각해서, 굳이 보여주려 하지 않아도 볼수 있지 않나
> > 생각했었는데, 만약 쪽지형식? 으로 1:1 대화 형식의 Feedback을 제공할거라면, 저도 이전 피드백에 대해 보여주는게 맞다고 생각합니다.
> 
> 네, 아무래도 커뮤니티로써 작용할 수도 있는 기능은 과감히 배제하자는 의견이 있었어서 쪽지 형태의 1:1 대화 내지 QnA 형태로 갈 것 같습니다.

오오... 커뮤니티 성격을 버리는건 정말 좋은 생각인거같습니다.
동의합니다!

**Comment by pjs0418** [comment]
해당 내용 수정해서 pull request 날리겠습니다!!
