### ISSUE TITLE
중복된 책 추가에 관한 Requirement 추가

### ISSUE THREAD

**Issue by d0lim** [2021-caucse-software-engineering/enhanced-library-management#54]
Guest를 추가하는 부분에서는 중복에 대한 추가를 제한한다는 Requirement 가 있는데  
책에 관한 부분에는 없습니다.   
추가해야 하지 않을까요?

**Comment by yulaseo** [comment]
책은 같은 책이라도 여러 권에 대해서 ID를 다르게 하냐, 같은 책이면 같은 ID를 사용하느냐에 따라 다르지 않을까요?

**Comment by cjdthsus2gh** [comment]
앞선 논의에서 ID를 각 종류마다가 아닌 각 권마다 부여하기로 결정했으니 자연스레 중복 예외처리가 될 것 같습니다.

**Comment by youngkwon02** [comment]
> Guest를 추가하는 부분에서는 중복에 대한 추가를 제한한다는 Requirement 가 있는데
> 책에 관한 부분에는 없습니다.
> 추가해야 하지 않을까요?

같은 제목의 책이라도, 각 한권 한권마다 ID값은 물론 다르게 부여되기는 합니다.
하지만 제목과 저자 이름이 같은 책이라면, 결국 새로 등록한다는 것은 수량이 증가된다는 의미이므로
중복되는 책을 추가하는 기능 자체를 제한하지 말고, 책을 추가할때 이미 존재하는 책과 같다는 기준을 만족하면
기존 존재하는 책의 수량을 변경하는 것이 어떨까 싶습니다.

**Comment by Beopsik** [comment]
특이한 경우이긴 하지만 한 사람이 같은 책을 서로 다른 날에 대여하고 두 권 모두 연체했을 경우, 책마다 연체료가 다를거니까 같은 종류의 책에도 다른 ID를 부여해야할 거 같습니다.

**Comment by Beopsik** [comment]
책을 같은 종류로 구별하는 것과 같은 종류의 책끼리의 구별이 필요하다면 ID를 두 가지 의미를 포함하게 하면 어떨까요?  ID가 10bit라면 앞에 4bit는 책종류를 구별하고 뒤에 6bit는 책의 고유번호를 부여하는 식으로요.

**Comment by pjs0418** [comment]
법식이 말대로 두 가지 정보가 모두 필요할 것 같습니다.

**Comment by yulaseo** [comment]
위 코멘트들 모두 동의합니다! ID에 저런 식으로 두 가지 정보를 담으면 이미 존재하는 책을 추가할 경우 책 수량 변경하는 것도 기준이 명확해지네요.

**Comment by d0lim** [comment]
PR 띄웠습니다! 언어적으로 부족한 부분 있을 수 있으니 도와주세요 ㅠㅠ
