### ISSUE TITLE
REQ-13과 REQ-14 내용 변경 논의

### ISSUE THREAD

**Issue by d0lim** [2021-caucse-software-engineering/enhanced-library-management#55]
Traceability Matrix를 만들어 고민하던 도중 
REQ-13의 내용은 반납 시에 책들의 정보와 전체 계산된 calculated fine을 보여주고, 
REQ14는 책 마다 fine을 계산해준다 라는 내용인 것을 확인하였습니다.  
이 내용이 저희 팀원들끼리 이야기 할 때에도 오해를 종종 불러일으키는 것 같아

REQ-13은 The system shall provide a function for checking book issue information such as book title, author, its location, issue period, overdue status, and calculated fine per book to a manager. 로 변경하여 책마다의 대출 정보를 보여주는 것으로 변경하고,
REQ-14는 The system shall provide a function for checking returning books' issue information such as book title, author, its location, issue period, overdue status, and calculated fine per guest to a manager. 로 변경하여 반납 시점의 전체 연체료를 포함한 대출 정보를 확인하는 것으로 변경하는 것이 어떨까 합니다.

의견 달아주시면 감사하겠습니다.

**Comment by youngkwon02** [comment]
동의합니다.

**Comment by Beopsik** [comment]
동의합니다.

**Comment by yulaseo** [comment]
그러면 REQ-13은 매니저가 연체자들을 책 별로 확인할 수 있는 기능을 말하는 건가요?

**Comment by d0lim** [comment]
> 그러면 REQ-13은 매니저가 연체자들을 책 별로 확인할 수 있는 기능을 말하는 건가요?

@yulaseo 말 그대로 그냥 대출된 책 별로 대출 정보를 보여주는 것으로 생각해 보았습니다! 매니저가 그냥 책들 각각의 대출 정보를 확인하는 기능으로요.

**Comment by yulaseo** [comment]
아하 이해됐습니다. 그러면 따로 연체료를 계산하는 기능은 명시하지 않는 건가요? 그냥 저 두 문장에 포함되니까 따로 기재하지 않나요?

**Comment by d0lim** [comment]
> 아하 이해됐습니다. 그러면 따로 연체료를 계산하는 기능은 명시하지 않는 건가요? 그냥 저 두 문장에 포함되니까 따로 기재하지 않나요?

사실 그 부분이 진짜 의논의 대상인 것 같기도 합니다.  
저는 그게 명시되어야 할 시스템의 기능이라고 생각하는 반면에 그렇지 않다고 생각하시는 분들도 있어서요.  
그러면 해당 내용에 대해서 어느 정도 합의점을 먼저 찾는 것이 중요할 것 같네요.  

@Beopsik @youngkwon02 @cjdthsus2gh @pjs0418 @yulaseo 연체료를 자동으로 계산한다는 내용이 기능적 요구로 REQ에 포함되어야 할지 의견들이 다른 분들의 궁금합니다.

**Comment by Beopsik** [comment]
연체료를 자동계산하는 것은 REQ에 명시되어야한다고 생각합니다.

**Comment by cjdthsus2gh** [comment]
저는 연체료 계산은 자동으로 계산돼서 출력되는 어떤...일종의 정보라는 생각을 갖고 있어서 기능이라고 할 수 없다는 입장이었는데, 위 Req13과 Req14에 대해서는 동의합니다.

**Comment by d0lim** [comment]
> 저는 연체료 계산은 자동으로 계산돼서 출력되는 어떤...일종의 정보라는 생각을 갖고 있어서 기능이라고 할 수 없다는 입장이었는데, 위 Req13과 Req14에 대해서는 동의합니다.

자동으로 계산한다는 것 자체를 기능이라고 생각해서 기능적 요구라고 볼 수 있지 않을까요?

**Comment by youngkwon02** [comment]
> > 아하 이해됐습니다. 그러면 따로 연체료를 계산하는 기능은 명시하지 않는 건가요? 그냥 저 두 문장에 포함되니까 따로 기재하지 않나요?
> 
> 사실 그 부분이 진짜 의논의 대상인 것 같기도 합니다.
> 저는 그게 명시되어야 할 시스템의 기능이라고 생각하는 반면에 그렇지 않다고 생각하시는 분들도 있어서요.
> 그러면 해당 내용에 대해서 어느 정도 합의점을 먼저 찾는 것이 중요할 것 같네요.
> 
> @Beopsik @youngkwon02 @cjdthsus2gh @pjs0418 @yulaseo 연체료를 자동으로 계산한다는 내용이 기능적 요구로 REQ에 포함되어야 할지 의견들이 다른 분들의 궁금합니다.


저는 시간이 지나면서 사용자가 책을 대여받은 날짜가 하루 하루 증가하는 것 처럼
연체료 계산도 이와 비슷한 맥락이라고 생각합니다.
사용자가 책을 대출받으면 사용자의 대출받아 소지하는 날짜가 자동으로 증가하는 것과 마찬가지로,
연체료 역시 시간이 지나, 연체일이 증가하면 연체료 역시 자동으로 값이 증가합니다.

하지만 저희는 사용자가 몇일동안 책을 소지했는가에 대한 시간 계산을 기능으로 명시하지 않았습니다.
왜냐하면 그냥 시스템 날짜에서 대출받을 날짜를 빼서 계산하면 구해지는 간단한 계산이기 때문이죠.

마찬가지로 연체료를 계산하는 거 역시, 복잡한 로직이 필요한 것이 아니고,
도서관에서 약속한 연체료 계산 공식에 연체된 날짜를 대입하면 얻어지는 간단한 값이며,
사용자는 연체료 계산 결과를 반납기능 등 어떤 기능상에서 눈으로 확인 할 수 있을 뿐이기 때문에
이를 별도의 기능요구에 포함시킬 필요가 없다고 생각합니다.

**Comment by youngkwon02** [comment]
> 저는 연체료 계산은 자동으로 계산돼서 출력되는 어떤...일종의 정보라는 생각을 갖고 있어서 기능이라고 할 수 없다는 입장이었는데, 위 Req13과 Req14에 대해서는 동의합니다.

저도 이와 비슷한 생각입니다.
그냥 시스템 상에서 항상 계산될 수 있는 값이라고 생각합니다.

**Comment by d0lim** [comment]
> > > 아하 이해됐습니다. 그러면 따로 연체료를 계산하는 기능은 명시하지 않는 건가요? 그냥 저 두 문장에 포함되니까 따로 기재하지 않나요?
> > 
> > 
> > 사실 그 부분이 진짜 의논의 대상인 것 같기도 합니다.
> > 저는 그게 명시되어야 할 시스템의 기능이라고 생각하는 반면에 그렇지 않다고 생각하시는 분들도 있어서요.
> > 그러면 해당 내용에 대해서 어느 정도 합의점을 먼저 찾는 것이 중요할 것 같네요.
> > @Beopsik @youngkwon02 @cjdthsus2gh @pjs0418 @yulaseo 연체료를 자동으로 계산한다는 내용이 기능적 요구로 REQ에 포함되어야 할지 의견들이 다른 분들의 궁금합니다.
> 
> 저는 시간이 지나면서 사용자가 책을 대여받은 날짜가 하루 하루 증가하는 것 처럼
> 연체료 계산도 이와 비슷한 맥락이라고 생각합니다.
> 사용자가 책을 대출받으면 사용자의 대출받아 소지하는 날짜가 자동으로 증가하는 것과 마찬가지로,
> 연체료 역시 시간이 지나, 연체일이 증가하면 연체료 역시 자동으로 값이 증가합니다.
> 
> 하지만 저희는 사용자가 몇일동안 책을 소지했는가에 대한 시간 계산을 기능으로 명시하지 않았습니다.
> 왜냐하면 그냥 시스템 날짜에서 대출받을 날짜를 빼서 계산하면 구해지는 간단한 계산이기 때문이죠.
> 
> 마찬가지로 연체료를 계산하는 거 역시, 복잡한 로직이 필요한 것이 아니고,
> 도서관에서 약속한 연체료 계산 공식에 연체된 날짜를 대입하면 얻어지는 간단한 값이며,
> 사용자는 연체료 계산 결과를 반납기능 등 어떤 기능상에서 눈으로 확인 할 수 있을 뿐이기 때문에
> 이를 별도의 기능요구에 포함시킬 필요가 없다고 생각합니다.

그렇다면 변경될 REQ-13, 14 정도의 표현으로 충분히 요구에 대해서 표현할 수 있을 것 같네요. 의견 감사합니다.

**Comment by Beopsik** [comment]
들어보니 맞는 말인거 같습니다. 동의합니다.

**Comment by yulaseo** [comment]
저도 동의합니다! 그렇다면 이 부분에 대한 UC(매니저 대출 정보 열람)도 두 개로 다시 쪼개야 할 것 같은데 제가 생각한 게 맞나요..? 아니면 UC 내에 success scenario를 둘로 쪼개도 되는건가요?

**Comment by pjs0418** [comment]
그렇다면 req-14를 삭제하고 req-13만 기존에 작성된 대로 살리는 방향으로 가도 되지 않을까요...? 연쳬료 자동 계산이 필요없다면 굳이 위에 처럼 per guest, per book으로 쪼개기 보다는 그냥 검색된 게스트의 대출 정보를 보여준다라고만 해도 될 것 같습니다.

**Comment by youngkwon02** [comment]
> 그렇다면 req-14를 삭제하고 req-13만 기존에 작성된 대로 살리는 방향으로 가도 되지 않을까요...? 연쳬료 자동 계산이 필요없다면 굳이 위에 처럼 per guest, per book으로 쪼개기 보다는 그냥 검색된 게스트의 대출 정보를 보여준다라고만 해도 될 것 같습니다.

근데 대출내역조회는 조회 자체의 기능이 존재하기 때문에 있어야 된다는 입장이긴한데...
뭔가 엄청 헷갈리긴 하네요 ㅠㅠ

저는 연체료 계산의 경우에는 정말 연체료만을 보여주는 별도의 메뉴가 없고, 다른 기능들에 있어서 연체료 값이 참조된다는 느낌이여서
기능에서 빼자는 입장이였는데,
대출 내역 조회같은경우는 별도의 기능이 존재하는거라서 있어야 한다는 입장.....

**Comment by pjs0418** [comment]
req-13도 대출 내역 조회라서 그 현재 req-14는 대출 내역 조회라는 기능이 아닙니다.....!!!

**Comment by d0lim** [comment]
그러니까 제가 14를 너무 어지럽게 써서 혼동이 생기는 것 같은데요,  
14에 넣고 싶은 내용은 게스트가 반납을 여러권 할 경우에 합쳐진 연체료를 매니저에게 제공한다는 것입니다.

**Comment by pjs0418** [comment]
제가 다시 생각을 해봤는데요 그냥 req-13, 14 원래대로 살리는 게 괜찮은 거 같습니다...

**Comment by yulaseo** [comment]
아 그러면 둘 다 게스트 검색 해서 REQ-13은 책 한 권 당 연체료를 보여주고, REQ-14는 게스트가 내야하는 전체 연체료를 보여준다는 건가요??! 처음에는 REQ-13은 책 검색 -> 책 클릭 -> 책 별로 대여해간 게스트를 보여줌, REQ-14는 게스트 검색 -> 게스트 클릭 -> 게스트 별로 대여한 책을 보여줌으로 이해했었어요!

**Comment by d0lim** [comment]
> 아 그러면 둘 다 게스트 검색 해서 REQ-13은 책 한 권 당 연체료를 보여주고, REQ-14는 게스트가 내야하는 전체 연체료를 보여준다는 건가요??! 처음에는 REQ-13은 책 검색 -> 책 클릭 -> 책 별로 대여해간 게스트를 보여줌, REQ-14는 게스트 검색 -> 게스트 클릭 -> 게스트 별로 대여한 책을 보여줌으로 이해했었어요!

네, 저는 그렇게 생각했습니다.  
마치 FIgma에 기술한 UI Requirment에서 Issue Book 하는 부분처럼 사실상 반납도 동일하다고 생각해서요.
그래서 Guest를 검색 -> 그 게스트가 빌린 책의 목록이 나옴 -> 이것이 REQ-13  
그 이후 반납할 책 들을 선택 -> 선택을 마침 -> 전체 연체료가 나옴 -> 이것이 REQ-14(변경될)  
이렇게 생각을 한 것입니다. 그런데, 아무래도 처음 보는 사람의 입장에서는 이 계산이 어떻게 이루어지는지에 대해서 명시하는 것이 좋지 않을까 해서 연체료를 계산하는 방식에 대해서 기능적 요구로 넣자는 것이구요.

**Comment by d0lim** [comment]
@cjdthsus2gh 그리고 오늘 말씀하신 오히려 NF인 것 같다는 말씀이 갑자기 기억나서 그러는데,  
24시간마다 연체료를 갱신한다 라는 것을 NF로 빼고,  
연체일에 따라 연체료를 계산한다 라는 것을 F로 그대로 두는게 어떨까요..?

**Comment by cjdthsus2gh** [comment]
> @cjdthsus2gh 그리고 오늘 말씀하신 오히려 NF인 것 같다는 말씀이 갑자기 기억나서 그러는데,
> 24시간마다 연체료를 갱신한다 라는 것을 NF로 빼고,
> 연체일에 따라 연체료를 계산한다 라는 것을 F로 그대로 두는게 어떨까요..?

네 그때 제가 하고싶던 말이 그거였습니다. 
그리고 대출내역조회에 관해서는 머리가 너무 엉켜서 조금 더 생각한 뒤 말씀드릴게요...

**Comment by yulaseo** [comment]
> > 아 그러면 둘 다 게스트 검색 해서 REQ-13은 책 한 권 당 연체료를 보여주고, REQ-14는 게스트가 내야하는 전체 연체료를 보여준다는 건가요??! 처음에는 REQ-13은 책 검색 -> 책 클릭 -> 책 별로 대여해간 게스트를 보여줌, REQ-14는 게스트 검색 -> 게스트 클릭 -> 게스트 별로 대여한 책을 보여줌으로 이해했었어요!
> 
> 네, 저는 그렇게 생각했습니다.
> 마치 FIgma에 기술한 UI Requirment에서 Issue Book 하는 부분처럼 사실상 반납도 동일하다고 생각해서요.
> 그래서 Guest를 검색 -> 그 게스트가 빌린 책의 목록이 나옴 -> 이것이 REQ-13
> 그 이후 반납할 책 들을 선택 -> 선택을 마침 -> 전체 연체료가 나옴 -> 이것이 REQ-14(변경될)
> 이렇게 생각을 한 것입니다. 그런데, 아무래도 처음 보는 사람의 입장에서는 이 계산이 어떻게 이루어지는지에 대해서 명시하는 것이 좋지 않을까 해서 연체료를 계산하는 방식에 대해서 기능적 요구로 넣자는 것이구요.

아하 딱 이해됐어요. 이 내용이 괜찮은데요!!

**Comment by pjs0418** [comment]
제가 다시 돌아왔는데요.... req-13을 좀 더 명확하게 위해서 조회된 게스트의 대출 내역 정보를 제공한다로 변경하고, req-14는 그대로 유지해서 책 별로 연체료를 자동 계산해주는 기능을 제공한다가 되는 건 어떤가요????? 여러 권을 반납할 때 해당되는 여러 권들의 전체 연체료를 계산하는 것도 필요할까요....???

**Comment by d0lim** [comment]
그럼 

기존의 REQ-14를 살리고
 Guest를 검색 -> **조회된 게스트의 대출 내역 정보 제공**
그 이후 반납할 책 들을 선택 -> 선택을 마침 -> **전체 연체료가 나옴**  
정도로 하면 어떨까요?

**Comment by d0lim** [comment]
전체 연체료를 계산하는 것도 UI Requirements에 명시되는 만큼, 기능적으로도 명시해주는 것이 맞을 것 같습니다..  
책을 빌리는 경우에도 Issuing List 에 들어갔던 책들을 한번에 대출한단 것을 요구로 명시했으니까요

**Comment by d0lim** [comment]
@cjdthsus2gh 책의 내용과 NF의 정의에 대해서 다시 찾아보니, 24시간에 한번 갱신된다는 것도 사실상 기능을 명시하는 것이라 기능적 요구에 해당하는 것 같습니다..

**Comment by pjs0418** [comment]
> 전체 연체료를 계산하는 것도 UI Requirements에 명시되는 만큼, 기능적으로도 명시해주는 것이 맞을 것 같습니다..
> 책을 빌리는 경우에도 Issuing List 에 들어갔던 책들을 한번에 대출한단 것을 요구로 명시했으니까요

그렇게 가시죠. 그러면 책을 여러권 반납할 수 있도록 returning list를 제공해야 한다와 returning list에 반납할 책을 추가할 수 있어야 한다 그리고 returning list에 담긴 책들을 반납하는 기능을 제공한다 까지 들어가야 하지 않을까요?

**Comment by d0lim** [comment]
> > 전체 연체료를 계산하는 것도 UI Requirements에 명시되는 만큼, 기능적으로도 명시해주는 것이 맞을 것 같습니다..
> > 책을 빌리는 경우에도 Issuing List 에 들어갔던 책들을 한번에 대출한단 것을 요구로 명시했으니까요
> 
> 그렇게 가시죠. 그러면 책을 여러권 반납할 수 있도록 returning list를 제공해야 한다와 returning list에 반납할 책을 추가할 수 있어야 한다 그리고 returning list에 담긴 책들을 반납하는 기능을 제공한다 까지 들어가야 하지 않을까요?

네,,, 그렇게 되는 게 맞겠네요.. 해당 내용까지 다 합쳐서 추가하는 것이 일관성을 가질 수 있을 것 같습니다.

**Comment by yulaseo** [comment]
오 returning list는 미처 생각해보지 않은 부분인데 추가하는 게 좋네요!

**Comment by youngkwon02** [comment]
> > 전체 연체료를 계산하는 것도 UI Requirements에 명시되는 만큼, 기능적으로도 명시해주는 것이 맞을 것 같습니다..
> > 책을 빌리는 경우에도 Issuing List 에 들어갔던 책들을 한번에 대출한단 것을 요구로 명시했으니까요
> 
> 그렇게 가시죠. 그러면 책을 여러권 반납할 수 있도록 returning list를 제공해야 한다와 returning list에 반납할 책을 추가할 수 있어야 한다 그리고 returning list에 담긴 책들을 반납하는 기능을 제공한다 까지 들어가야 하지 않을까요?

네네! 동의합니당

**Comment by Beopsik** [comment]
동의합니다

**Comment by cjdthsus2gh** [comment]
동의합니다

**Comment by d0lim** [comment]
넵, 그러면 해당 내용 다 참고해서 잘 작성 이후 PR 날리도록 하겠습니다.
